#!/bin/bash

#+---------------------------------------+
#| dpaste                                |
#| author: Donald Merand                 |
#+---------------------------------------+
#| post a message to dpaste              |
#+---------------------------------------+

HOST='http://dpaste.com/api/v1/'
TITLE="Post from CLI"
POSTER="TheCommandLine"
LANGUAGE="Bash" 
HOLD=0

show_help() {
  cat <<HELP
DPASTE SENDER

Usage - \`dpaste <options>\`
  (or use a pipe eg: \`cat <file> | dpaste <options>\`

Options:
  -h - Show this help screen
  -o - "hold" the paste for 30 days
  -t <title> - Specify title
  -p <poster> - Specify poster
  -l <lang> - Specify language
    language can be Python, SQL, CSS, XML, Diff, Ruby, Apache, Bash, etc.
HELP
}

#test for existence of required programs
test_existence() {
  program=$1
  which ${program} &> /dev/null;

  if [[ "$?" != "0" ]];
  then
    echo "'$program' appears to not be installed, check your PATH variable"
    exit 1
  fi
}

test_existence curl

while getopts ":hot:p:l:" OPTNAME
do
  case "$OPTNAME" in
    "h")
      show_help
      exit
      ;;
    "o")
      HOLD=1
      ;;
    "t")
      TITLE=$OPTARG
      ;;
    "p")
      POSTER=$OPTARG
      ;;
    "l")
      LANGUAGE=$OPTARG
      ;;
    "?")
      echo "Unknown option $OPTARG"
      ;;
    ":")
      echo "No argument value for option $OPTARG"
      ;;
    *)
    # Should not occur
      echo "Unknown error while processing options"
      ;;
  esac
done

#now actually send the message
#     vv silent, show headers in output
curl -si \
  -F 'content=<-' \
  -F "title=$TITLE" \
  -F "language=$LANGUAGE" \
  -F "poster=$POSTER" \
  -F "hold=$HOLD" \
  "$HOST" |
  
#filter out the location from the result
#got this code thanks to http://news.e-scribe.com/427
grep ^Location: | colrm 1 10 
