#!/usr/bin/env ruby

num_repeats = ARGV.shift
exit 1 if num_repeats.nil?
exit 1 unless num_repeats[/\d/]
num_repeats = num_repeats.to_i
exit 1 if num_repeats < 1


result = []

num_repeats.times do
  result << `curl -s http://randomword.setgetgo.com/get.php`.gsub("\r\n", "").downcase
end

puts result.join " "
