#!/usr/bin/env ruby

# Generate a random string.
#
# `randompass NUM` will make the password `NUM` characters in length

if ARGV[0].nil?
  length = 8
else
  length = ARGV[0].to_i
end

puts rand(36**length).to_s(36)
