#!/usr/bin/env ruby
#---------------------------------------------------------#
# timer
# Donald L. Merand
# ----------------
# Google has a great timer. Why not be able to call it from
# the command line? You can with this, and it auto-
# backgrounds your web browser so you can keep working.
#---------------------------------------------------------#


require 'uri'

if ARGV.empty?
  puts "usage: timer 1 minute (or some other time)"
  exit 1
end

base_search_url="https://encrypted.google.com/search?hl=en&q="
arg = ARGV.join " "
arg = URI.escape "timer #{arg}"

#          vv don't foreground the timer
exec "open -g '#{base_search_url}#{arg}'"
